### ISSUE TITLE
Ahem

### ISSUE THREAD

**Issue by Scaratek** [MadjikDotPng/MadjikDotPng.github.io#1]
i think your missing something >:(

do you not love me :(

**Comment by Scaratek** [comment]
@MadjikDotPng :sob:
do you not love me :(

**Comment by Scaratek** [comment]
hellllllllllllllllo
:(

**Comment by Scaratek** [comment]
am gonna sob
 :((((
i miss u

**Comment by MadjikDotPng** [comment]
i lov u

**Comment by Scaratek** [comment]
yayy
i love youu too
